java_test(
    name = "oauth",
    test_class = "com.meab.oauth.GitHubServletTest",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/com/meab/oauth",
        "@com_google_truth//jar",
        "@javax_servlet_api//jar",
        "@org_junit//jar",
        "@org_mockito//jar",
    ]
)
