java_library(
    name = "servlet",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/com/meab/api:__pkg__",
        "//src/main/java/com/meab/subscriptions:__pkg__",
    ],
    deps = [
        "//src/main/java/com/meab/user",
        "@javax_servlet_api//jar",
    ],
)
