java_library(
    name = "migration",
    srcs = glob(["*.java"]),
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//src/main/java/com/meab",
        "@com_google_appengine_java//:api",
        "@guava//jar",
        "@javax_servlet_api//jar",
        "@json//jar",
    ],
)