java_library(
    name = "user",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/com/meab",
        "@apache_httpclient//jar",
        "@apache_httpcore//jar",
        "@autovalue//:processor",
        "@com_google_appengine_java//:api",
        "@guava//jar",
        "@javax_servlet_api//jar",
        "@json//jar",
        "@jsr305//jar",
    ],
    visibility = [
        "//src/main/java:__subpackages__",
    ],
)
