java_binary(
    name = "backend",
    main_class = "does.not.exist",
    runtime_deps = [
        "//src/main/java/com/meab/api",
        "//src/main/java/com/meab/oauth",
        "//src/main/java/com/meab/subscriptions",
    ],
    visibility = ["//:__pkg__"]
)
