java_library(
    name = "ui",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/com/meab",
        "@freemarker//jar",
        "@guava//jar",
        "@javax_servlet_api//jar",
    ],
    visibility = ["//src/main/java:__pkg__"],
)
