java_library(
    name = "dev",
    srcs = glob(["*.java"]),
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "@com_google_appengine_java//:api",
        "@guava//jar",
        "@javax_servlet_api//jar",
        "@json//jar",
    ]
)