package com.meab.dev;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

/**
 * Testing servlet mimicking GitHub notification API.
 */
public class Notifications extends DevServlet {
  @Override
  public void get(HttpServletRequest request, HttpServletResponse response) throws IOException {
    response.getWriter().write("[{\"id\":\"110016637\",\"updated_at\":\"2017-04-24T14:53:25Z\",\"repository\":{\"private\":false,\"id\":20773773,\"description\":\"Correct, reproducible, and fast builds for everyone.\",\"name\":\"bazel\",\"fork\":false,\"owner\":{\"avatar_url\":\"https://avatars2.githubusercontent.com/u/11684617?v=3\",\"gravatar_id\":\"\",\"site_admin\":false,\"type\":\"Organization\",\"url\":\"https://api.github.com/users/bazelbuild\",\"id\":11684617,\"html_url\":\"https://github.com/bazelbuild\",\"login\":\"bazelbuild\"},\"full_name\":\"bazelbuild/bazel\"},\"reason\":\"subscribed\",\"subject\":{\"title\":\"Docker build rule doesn't work at the top level\",\"type\":\"Issue\",\"url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/616\",\"latest_comment_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/616\"},\"unread\":true,\"last_read_at\":null,\"url\":\"https://api.github.com/notifications/threads/110016637\"},\n" +
      "{\"id\":\"113677963\",\"updated_at\":\"2017-01-23T22:18:38Z\",\"repository\":{\"private\":false,\"id\":45717250,\"downloads_url\":\"https://api.github.com/repos/tensorflow/tensorflow/downloads\",\"milestones_url\":\"https://api.github.com/repos/tensorflow/tensorflow/milestones{/number}\",\"comments_url\":\"https://api.github.com/repos/tensorflow/tensorflow/comments{/number}\",\"description\":\"Computation using data flow graphs for scalable machine learning\",\"name\":\"tensorflow\",\"fork\":false,\"issues_url\":\"https://api.github.com/repos/tensorflow/tensorflow/issues{/number}\",\"url\":\"https://api.github.com/repos/tensorflow/tensorflow\",\"html_url\":\"https://github.com/tensorflow/tensorflow\",\"owner\":{\"received_events_url\":\"https://api.github.com/users/tensorflow/received_events\",\"organizations_url\":\"https://api.github.com/users/tensorflow/orgs\",\"avatar_url\":\"https://avatars2.githubusercontent.com/u/15658638?v=3\",\"gravatar_id\":\"\",\"gists_url\":\"https://api.github.com/users/tensorflow/gists{/gist_id}\",\"starred_url\":\"https://api.github.com/users/tensorflow/starred{/owner}{/repo}\",\"site_admin\":false,\"type\":\"Organization\",\"url\":\"https://api.github.com/users/tensorflow\",\"id\":15658638,\"html_url\":\"https://github.com/tensorflow\",\"following_url\":\"https://api.github.com/users/tensorflow/following{/other_user}\",\"events_url\":\"https://api.github.com/users/tensorflow/events{/privacy}\",\"login\":\"tensorflow\",\"subscriptions_url\":\"https://api.github.com/users/tensorflow/subscriptions\",\"repos_url\":\"https://api.github.com/users/tensorflow/repos\",\"followers_url\":\"https://api.github.com/users/tensorflow/followers\"},\"statuses_url\":\"https://api.github.com/repos/tensorflow/tensorflow/statuses/{sha}\",\"issue_events_url\":\"https://api.github.com/repos/tensorflow/tensorflow/issues/events{/number}\",\"labels_url\":\"https://api.github.com/repos/tensorflow/tensorflow/labels{/name}\",\"issue_comment_url\":\"https://api.github.com/repos/tensorflow/tensorflow/issues/comments{/number}\",\"tags_url\":\"https://api.github.com/repos/tensorflow/tensorflow/tags\",\"contents_url\":\"https://api.github.com/repos/tensorflow/tensorflow/contents/{+path}\",\"full_name\":\"tensorflow/tensorflow\"},\"reason\":\"mention\",\"subscription_url\":\"https://api.github.com/notifications/threads/113677963/subscription\",\"subject\":{\"title\":\"bazel build error for PolymerElements\",\"type\":\"Issue\",\"url\":\"https://api.github.com/repos/tensorflow/tensorflow/issues/452\",\"latest_comment_url\":\"https://api.github.com/repos/tensorflow/tensorflow/issues/comments/274635704\"},\"unread\":true,\"last_read_at\":\"2016-05-14T11:33:20Z\",\"url\":\"https://api.github.com/notifications/threads/113677963\"},\n" +
      "{\"id\":\"117014533\",\"updated_at\":\"2016-12-09T14:24:25Z\",\"repository\":{\"private\":false,\"id\":20773773,\"downloads_url\":\"https://api.github.com/repos/bazelbuild/bazel/downloads\",\"milestones_url\":\"https://api.github.com/repos/bazelbuild/bazel/milestones{/number}\",\"comments_url\":\"https://api.github.com/repos/bazelbuild/bazel/comments{/number}\",\"description\":\"Correct, reproducible, and fast builds for everyone.\",\"name\":\"bazel\",\"events_url\":\"https://api.github.com/repos/bazelbuild/bazel/events\",\"fork\":false,\"url\":\"https://api.github.com/repos/bazelbuild/bazel\",\"html_url\":\"https://github.com/bazelbuild/bazel\",\"owner\":{\"avatar_url\":\"https://avatars2.githubusercontent.com/u/11684617?v=3\",\"gravatar_id\":\"\",\"site_admin\":false,\"type\":\"Organization\",\"url\":\"https://api.github.com/users/bazelbuild\",\"id\":11684617,\"html_url\":\"https://github.com/bazelbuild\",\"following_url\":\"https://api.github.com/users/bazelbuild/following{/other_user}\",\"events_url\":\"https://api.github.com/users/bazelbuild/events{/privacy}\",\"login\":\"bazelbuild\",\"subscriptions_url\":\"https://api.github.com/users/bazelbuild/subscriptions\",\"repos_url\":\"https://api.github.com/users/bazelbuild/repos\",\"followers_url\":\"https://api.github.com/users/bazelbuild/followers\"},\"statuses_url\":\"https://api.github.com/repos/bazelbuild/bazel/statuses/{sha}\",\"issue_events_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/events{/number}\",\"labels_url\":\"https://api.github.com/repos/bazelbuild/bazel/labels{/name}\",\"issue_comment_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/comments{/number}\",\"tags_url\":\"https://api.github.com/repos/bazelbuild/bazel/tags\",\"contents_url\":\"https://api.github.com/repos/bazelbuild/bazel/contents/{+path}\",\"full_name\":\"bazelbuild/bazel\"},\"reason\":\"comment\",\"subscription_url\":\"https://api.github.com/notifications/threads/117014533/subscription\",\"subject\":{\"title\":\"Different sys.path between bazel test and bazel run\",\"type\":\"Issue\",\"url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/753\",\"latest_comment_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/753\"},\"unread\":true,\"last_read_at\":null,\"url\":\"https://api.github.com/notifications/threads/117014533\"},\n" +
      "{\"id\":\"110545231\",\"updated_at\":\"2016-12-08T17:33:00Z\",\"repository\":{\"private\":false,\"id\":20773773,\"comments_url\":\"https://api.github.com/repos/bazelbuild/bazel/comments{/number}\",\"description\":\"Correct, reproducible, and fast builds for everyone.\",\"name\":\"bazel\",\"events_url\":\"https://api.github.com/repos/bazelbuild/bazel/events\",\"archive_url\":\"https://api.github.com/repos/bazelbuild/bazel/{archive_format}{/ref}\",\"fork\":false,\"url\":\"https://api.github.com/repos/bazelbuild/bazel\",\"html_url\":\"https://github.com/bazelbuild/bazel\",\"owner\":{\"avatar_url\":\"https://avatars2.githubusercontent.com/u/11684617?v=3\",\"gravatar_id\":\"\",\"site_admin\":false,\"type\":\"Organization\",\"url\":\"https://api.github.com/users/bazelbuild\",\"id\":11684617,\"html_url\":\"https://github.com/bazelbuild\",\"login\":\"bazelbuild\",\"repos_url\":\"https://api.github.com/users/bazelbuild/repos\",\"followers_url\":\"https://api.github.com/users/bazelbuild/followers\"},\"statuses_url\":\"https://api.github.com/repos/bazelbuild/bazel/statuses/{sha}\",\"issue_events_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/events{/number}\",\"labels_url\":\"https://api.github.com/repos/bazelbuild/bazel/labels{/name}\",\"issue_comment_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/comments{/number}\",\"tags_url\":\"https://api.github.com/repos/bazelbuild/bazel/tags\",\"contents_url\":\"https://api.github.com/repos/bazelbuild/bazel/contents/{+path}\",\"full_name\":\"bazelbuild/bazel\"},\"reason\":\"assign\",\"subscription_url\":\"https://api.github.com/notifications/threads/110545231/subscription\",\"subject\":{\"title\":\"setup-intellij.sh says it can't find ijar\",\"type\":\"Issue\",\"url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/628\",\"latest_comment_url\":\"https://api.github.com/repos/bazelbuild/bazel/issues/comments/265802092\"},\"unread\":true,\"last_read_at\":null,\"url\":\"https://api.github.com/notifications/threads/110545231\"}]");
  }
}
