java_library(
    name = "meab",
    srcs = glob(["*.java"]),
    visibility = ["//src/main/java/com/meab:__subpackages__"],
    deps = [
        "@com_google_appengine_java//:api",
        "@freemarker//jar",
        "@javax_servlet_api//jar",
    ]
)
