java_library(
    name = "oauth",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java:__pkg__",
        "//src/test/java/com/meab/oauth:__pkg__"
    ],
    deps = [
        "@apache_httpclient//jar",
        "@com_google_appengine_java//:api",
        "@apache_httpcore//jar",
        "@commons_codec//jar",
        "@commons_logging//jar",
        "@guava//jar",
        "@javax_servlet_api//jar",
    ],
)

