java_test(
    name = "NotificationDatastoreTest",
    srcs = ["NotificationDatastoreTest.java"],
    deps = [
        "//src/main/java/com/meab",
        "//src/main/java/com/meab/notifications",
        "//src/main/java/com/meab/user",
        "@com_google_appengine_java//:api",
        "@com_google_appengine_java//:jars",
        "@json//jar",
        "@org_junit//jar",
        "@org_mockito//jar",
    ],
)