java_library(
    name = "subscriptions",
    srcs = glob(["*.java"]),
    visibility = ["//src/main/java:__pkg__"],
    deps = [
        "//src/main/java/com/meab",
        "//src/main/java/com/meab/servlet",
        "//src/main/java/com/meab/user",
        "@com_google_appengine_java//:api",
        "@gson//jar",
        "@guava//jar",
        "@javax_servlet_api//jar",
        "@stripe//jar",
    ],
)
